### PR TITLE
fix(updater): npm7 package lock's inner version not being updated

### PR DESCRIPTION
**Pull request by vicrep**
NPM v7 introduces a new package-lock.json version, which now stores the project's version in two places: `lock.version` and `lock.packages[''].version`. This updates `writeVersion` to also bump the latter if present in the file.

Please let me know if you have any further questions.

### CODE REVIEW

**Comment by vicrep** [comment]
Hi @bcoe , sorry for bothering you and please forward to someone else if more appropriate.

I was wondering if there was any chance of having this PR looked at sometime soon. I'm not the only one dealing with this issue, and it's creating a lot of noise for my projects which use renovate / automatic package-lock maintenance. Many thanks! :)

**Comment by rusekr** [comment]
+100. for npm 7 without this patch people must write custom updaters.

**Comment by rusekr** [comment]
Updater for npm-shrinkwrap v2 instead of json to use in config with no dependencies:

```
'use strict';
// updater for standard-version
module.exports.readVersion = function (contents) {
  return JSON.parse(contents).version;
};

module.exports.writeVersion = function (contents, version) {
  const json = JSON.parse(contents);
  json.version = version;
  if (json.packages && json.packages['']) {
    json.packages[''].version = version;
  }
  return JSON.stringify(json, null, 2) + '\n'; // like npm defaults
};

```

**Comment by vicrep** [comment]
Hi @rusekr, are you asking me to rebase this branch / clean up history? I usually squash and merge PRs to keep master clean :)

**Comment by rusekr** [comment]
> Hi @rusekr, are you asking me to rebase this branch / clean up history? I usually squash and merge PRs to keep master clean :)

Just saw "Comits 3"  on tab here and thought what big in this patch then saw all changes which a small and from first commit

**Comment by vicrep** [comment]
Hi @jbottigliero and @bcoe , sorry for pinging you directly, but this PR has been open for almost 6 months, and brings a relatively simple / nice QoL fix related to NPM7, I would greatly appreciate if you could take a look :) Many thanks!

(Also, it seems I'm not the only one requesting this, it's currently the second most upvoted open PR in the project).

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@vicrep thank you for the nudge.

**Pull request merged**
