### PR TITLE
feat: add .cjs config file

### LINKED ISSUE #680: [Request] Add '.cjs' as a valid extension for config files.
I have been migrating to ES modules for my Node projects, and I'd like to use `.versionrc.cjs` for Node.js projects instead of `.versionrc.js`. It looks like all that needs to happen is to add `.versionrc.cjs` to the array of valid configs in https://github.com/conventional-changelog/standard-version/blob/master/lib/configuration.js. I'd be happy to submit a PR adding this as an option.

### PR DESCRIPTION
**Pull request by shirotech**
Fixes #680

### CODE REVIEW

**Comment by ghost91-** [comment]
Any info on this? Is anything blocking it from being merged? I would love to be able to use the `.cjs` extension.

**Comment by chimericdream** [comment]
Bump. Is there anything in particular holding this up?

**Comment by lhokktyn** [comment]
👍 Most of our codebases will be moving to ESM so It would be great to have this feature available.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@shirotech thanks for the patch 👍 

Appologies that this codebase is realtively stagnent these days, I've been working more on:

https://github.com/googleapis/release-please

**Comment by shir0u** [comment]
@bcoe All good, it's only been 11 months. By the way, Happy new year, and thanks for the merge! 👍

**Comment by lukasreinfurt** [comment]
I can't find this release in the npm registry, any idea why?

**Pull request merged**
