### PR TITLE
feat: add support for `package-lock.json`

### PR DESCRIPTION
**Pull request by noreiller**

### CODE REVIEW

**Comment by stevemao** [comment]
We have a bunch of `write...Json()`s. Should probably abstract them into a function sometime.

**Comment by noreiller** [comment]
I wanted to do so, but I had a doubt about this.

**Comment by stevemao** [comment]
@noreiller oops I merged this. Feel free to refactor the code and send a PR :)

**Comment by Tmarty** [comment]
Are merged changes automatically available in standard-version@next?

**Comment by bcoe** [comment]
@Tmarty @noreiller please give `4.2.0` a try \o/ adds a lot of cool features and would love people to take it for a spin.

**Comment by Tmarty** [comment]
@bcoe @noreiller  this works like a charm in 4.2.0 :tada:

**Comment by noreiller** [comment]
Hi, the last version works great, thanks!

**Pull request merged**
