### PR TITLE
feat: add --lerna-package flag used to extract tags in case of lerna repo

### PR DESCRIPTION
**Pull request by micaelmbagira**
The package [conventional-recommended-bump](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump) allows a `lernaPackage` option. See [conventional-recommended-bump/index.js#L64-L65](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-recommended-bump/index.js#L64-L65)

This PR exposes this flag in the `standard-version` options and pass it along to `conventional-recommended-bump`

### CODE REVIEW

**Comment by micaelmbagira** [comment]
@bcoe @jbottigliero What do you think?

**Comment by palash2601** [comment]
Hello,

We are looking forward to use standard-version for our monorepo. Any plans to merge this PR?

**Comment by bcoe** [comment]
@micaelmbagira apologies for dropping this PR on the floor for so long, I appreciate the contribution.

@palash2601 I see no reason not to land this as soon as tests pass 👍

**Review by bcoe — APPROVED** [review]

**Comment by gaurav5430** [comment]
How is this supposed to be used with a lerna setup?

Should it replace the conventional-commits setup that lerna provides by default ?

**Comment by kkazala** [comment]
Is there support for lerna independent mode?

**Pull request merged**
