### PR TITLE
feat(options): add the ability to skip bump/changelog phase by using …

### LINKED ISSUE #157: How to bump/generate changelog and commit/push in a second time
Hello,

I need to embed the version number and the changelog in the generated artifact of my application.

So I would like to be able to bump the version and generate the changelog first, then build my application, then create the commit, tag and push everything.

How to do that with standard-version ?

Thanks in advance for your help

### PR DESCRIPTION
**Pull request by denouche**
…--skip-bump-and-changelog option, and to skip the commit/tag/push phase by using --skip-commit option

closes #157

### CODE REVIEW

**Comment by Tapppi** [comment]
Lets wait for the discussion in #157 first, and then decide the fate of this!

**Comment by stevemao** [comment]
I like the option, `skip-commit`, but not the other one :)

**Comment by Tapppi** [comment]
@stevemao I agree, even if this is not necessary for htis use case once we get started on hooks, it might be worthwile anyway.

**Comment by bcoe** [comment]
@Tapppi @stevemao @lancecaraccioli I like the idea of enumerating a set of lifecycles that occur in `standard-verison`:

`pre-commit`
`pre-changelog`
`pre-tag`

...

then it would be neat to allow any of these steps to be skipped within reason -- it would also be nice to try to isolate the logic for each so that, within reason, we can perform a rollback.

**Comment by lancecaraccioli** [comment]
@bcoe I was thinking an incremental approach would make sense here.  Let's put the infrastructure in place to call hooks first. Then let the community add hooks  (via PR) based on their concrete use cases. I'll try to update my PR for #157 today based on discussion there.

**Comment by bcoe** [comment]
@lancecaraccioli @denouche it's looking like the initial `hooks` work is close to landing; once this is polished with documentation, etc; I think we should then use this as the foundation for adding the support for skipping specific lifecycle hooks.

**Comment by bcoe** [comment]
closing in favor of: https://github.com/conventional-changelog/standard-version/pull/188

**Pull request closed without merging**
