### PR TITLE
fix: update commit msg for when using commitAll

### PR DESCRIPTION
**Pull request by vidavidorra**
The commit message now shows that all staged files are committed too.

### CODE REVIEW

**Comment by vidavidorra** [comment]
I'm fixing the failures. Just noted the local tests too, so I'll check them and update this!

**Comment by vidavidorra** [comment]
I've updated this and did now pass local tests. Would an additional test for this be necessary? If so, under which category should this be `cli`?

**Comment by stevemao** [comment]
> Would an additional test for this be necessary?

Yes please :)

**Comment by vidavidorra** [comment]
@stevemao I've added the tests under the `cli` category. Both a test for the case without the message and with the message is added.

```shell
  cli
    ...
    ✓ preserves line feed in package.json (4592ms)
    ✓ preserves carriage return + line feed in package.json (3544ms)
    ✓ does not run git hooks if the --no-verify flag is passed (7047ms)
    ✓ does not print output when the --silent flag is passed (3296ms)
    ✓ does not display `npm publish` if the package is private (3264ms)
    ✓ does not display `all staged files` without the --commit-all flag (3501ms)
    ✓ does display `all staged files` when the --commit-all flag is passed (3708ms)
    ✓ includes merge commits (8785ms)
    ✓ exits with error code if "scripts" is not an object (3288ms)
    ...
```

**Comment by bcoe** [comment]
@vidavidorra could you share what the full console output ends up looking like? It's hard for me to gauge if it looks pretty, based just on the assertions.

**Comment by vidavidorra** [comment]
@bcoe The console output now looks like this. Note that I'm executing standard-version twice, see #315 for the `release` and `release:ok` scripts.

```shell
$ npm run release -- --dry-run             

> tools@0.2.0 release /home/jdebruijn/projects/tools
> standard-version --skip.commit --skip.tag "--dry-run"

✔ bumping version in package.json from 0.2.0 to 0.2.1
✔ bumping version in package-lock.json from 0.2.0 to 0.2.1
✔ Running lifecycle script "postbump"
ℹ - execute command: "npm run prettier:package"
✔ outputting changes to CHANGELOG.md

---
<a name="0.2.1"></a>
## [0.2.1](https://github.com/vidavidorra/tools/compare/v0.2.0...v0.2.1) (2019-04-04)


### Bug Fixes

* npm moderatte severity vulnerabilities ([0ae5d02](https://github.com/vidavidorra/tools/commit/0ae5d02))
---

✔ Running lifecycle script "postchangelog"
ℹ - execute command: "npm run prettier:changelog"

$ npm run release:ok -- --dry-run

> tools@0.2.0 release:ok /home/jdebruijn/projects/tools
> standard-version --sign --commit-all --skip.bump --skip.changelog "--dry-run"

✔ Running lifecycle script "precommit"
ℹ - execute command: "git add CHANGELOG.md package*.json"
✔ committing CHANGELOG.md and all staged files
✔ tagging release v0.2.0
ℹ Run `git push --follow-tags origin master && npm publish` to publish

```

**Pull request merged**
