### PR TITLE
fix: correct changelog spelling in header

### PR DESCRIPTION
**Pull request by cristovaov**
In my opinion this is just a spelling mistake and not a breaking change.

### CODE REVIEW

**Comment by jbottigliero** [comment]
Going to link this to #299 for tracking, but this looks good to me.

**Comment by bcoe** [comment]
@cristovaov I kind of think this is a point of opinion, looking at:

https://keepachangelog.com/en/0.3.0/

They use the term `Change Log` throughout the site ... what if you instead refactor it so that you can pass in the header in configuration?

**Comment by cristovaov** [comment]
@bcoe I'd respectfully argue why I believe (or opine) `change log` to be a spelling mistake :)

They've passed to 1.0.0 for while now: https://keepachangelog.com/en/1.0.0/ 
where all references to "change log" were changed to "changelog" in that version.
I've looked up what was grammarly correct but admit that it's somewhat:
1. The Free Dictionary:
   * [points 'changelog' to their encyclopedia article and Wikipedia (as mentioned in #299)](https://keepachangelog.com/en/1.0.0/]) and quite extensive.
   * [points 'change log' has just one line and directs to see `change file`.
2. Mirriam-Webster has no entry for 'changelog' nor 'change log'.
3. Oxford Dictionary:
   * [has no entry for 'changelog' but has one though for 'change log'](https://en.oxforddictionaries.com/definition/change_log)
 However despite 3, `changelog` seems to be the accepted and correct spelling. Also see issue [#92](https://github.com/olivierlacan/keep-a-changelog/pull/92) on keep-a-changelog.

This said, I'm not sure if I'm knowledgeable enough to make the header configurable. I could give it a go at the weekend perhaps!

**Comment by bcoe** [comment]
addressed in https://github.com/conventional-changelog/standard-version/pull/335, you convinced me of the spelling 😄

**Comment by cristovaov** [comment]
Thank you @bcoe !

**Pull request closed without merging**
