### PR TITLE
feat: manifest.json support

### PR DESCRIPTION
**Pull request by fent**
Hi there,

I've added support for updating a `manifest.json` file, which is used in Google Chrome extensions. 
There's potential in standard-release to be used for software packages that are not node.js related or don't use npm. And I think this is a good start towards that.

Thank you for this tool btw, it's helped me a lot!

### CODE REVIEW

**Comment by stevemao** [comment]
I guess we could merge this before we come up with a plugin strategy?

**Comment by fent** [comment]
Just noticed I left the `.only` on the test. But now some other tests fail.

Will try to figure out why.

**Comment by MAGALY956** [comment]
Y<a class="twitter-timeline" href="https://twitter.com/ThePSF?ref_src=twsrc%5Etfw">Tweets by ThePSF</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by bcoe** [comment]
@fent I like this refactor.

**Comment by bcoe** [comment]
@fent please try, `npm i standard-version@next` it should have your changes.

**Pull request merged**
