### PR TITLE
Suggestions to improve README

### PR DESCRIPTION
**Pull request by nexdrew**
Highlights:

1. Update links to account for new GitHub org
2. Attempt to clarify commands and steps in **how it works:**
3. Expand **Installation** section to show options for npm run script and global bin
4. Add **Usage** section (and move **Initial CHANGELOG.md Generation** under it)
5. ~~Explain how to use a _prepublish_ lifecycle script in the **Automating** section~~ Remove **Automating** section

Note that this **does not** attempt to address concerns in #3.

Let me know what you think.

### CODE REVIEW

**Comment by bcoe** [comment]
@nexdrew mind updating this to reflect what we've been discussing (making standard-version a replacement for `npm version`).

**Comment by nexdrew** [comment]
@bcoe Will do!

**Comment by nexdrew** [comment]
@bcoe Rebased and updated.

**Comment by bcoe** [comment]
@nexdrew managed to make this out of date on you again, sorry; mind giving the current README.md on master another set of eyes, I tried to incorporate your suggestions, but I think there are some other edits we'll want to pull over from this.

**Comment by nexdrew** [comment]
Closing in favor of #26

**Pull request closed without merging**
