### PR TITLE
docs(readme): add guidelines for release branches as per #130

### PR DESCRIPTION
**Pull request by fritzvd**
Hi,

I took some time to merge some of the comments for the README, mostly based on @Tapppi's comments. Sorry it took a week longer to find the time.

If something is unclear or inaccurate I'll gladly change it.

Cheers,

Fritz

### CODE REVIEW

**Comment by fritzvd** [comment]
Whoops sorry haven’t found the time to get back to this. I’ll probably have some more time next week

Fritz

+31 (0) 6 16 058 218
pgp public key: https://keybase.io/fritzvd/key.asc

**Comment by bcoe** [comment]
@fritzvd awesome, thanks for adding this content; One thing that comes to my mind is I would love a better story for pre-releases;

I find releasing from `master` is rarely an issue once code is ready to go out the door; but I often find I want to release intermediate library versions from a branch (usually this release is related to a specific ticket):

https://github.com/yargs/yargs/pull/741#issuecomment-269588507

maybe we could make the CHANGELOG generation logic slightly different for a prerelease; perhaps it's as simple as:

1. default to adding a row to the CHANGELOG that does not enumerate bugs, patches, etc., and simply points out that the pre-release was released at a given tag:

-----

## 4.0.0-0 (2016-12-02) Prerelease

**pre-release 4.0.0-0**

-----

2. optionally allow people to specify a prerelease message during generation; apply the same GitHub ticket/username replacement when plopping this in the README.md.

CC: @Tapppi, @stevemao any ways! just brain dumping here 👍 not a blocker for this issue.

**Comment by bcoe** [comment]
@fritzvd just swinging through some old issues, and prodding people, still think this is worth landing?

**Comment by fritzvd** [comment]
hi @bcoe and @Tapppi I'm not sure you should land my PR. perhaps with the new changes @bcoe suggested for the pre-release it's kind of redundant?

Otherwise it might be better if @Tapppi refactors the content, because I don't think I could help out making it the way he should.
Or it would be so much of a back and forth, it would just be more efficient if @Tapppi changes it himself. Does that make sense?

**Comment by bcoe** [comment]
@Tapppi any thoughts on this; maybe it would make sense to close this for the time being, and revisit once we address some of the new API changes in the works, e.g., lifecyle hooks.

**Comment by bcoe** [comment]
this is a bit out of sync now, as we've been working on other features -- let's take another 🔪 at improving docs once we've landed a few of the neat features currently on the wire.

**Comment by fritzvd** [comment]
👍🏼

**Pull request closed without merging**
