### PR TITLE
Feature/append publish message after success

### PR DESCRIPTION
**Pull request by tomchentw**
Thanks for creating this package! It's not only awesome but also aligned with my best practices so I use it like at home. Just one more thing to add:

screen shot 2016-05-30 at 6 29 28 pm

### CODE REVIEW

**Comment by tomchentw** [comment]
Thanks for creating this package! It's not only awesome but also aligned with my best practices so I use it like at home. Just one more thing to add:

screen shot 2016-05-30 at 10 58 00 am

**Comment by stevemao** [comment]
Looks good :) maybe a bit less verbose?

**Comment by tomchentw** [comment]
@stevemao any suggested wording? I'm okay with any wording here. Just let me know so that I can change it.

**Comment by stevemao** [comment]
I'd let @bcoe to make the call. But I'd probably just say "Run `git push --follow-tags origin master; npm publish` to publish."

**Comment by tomchentw** [comment]
Updated for now.

**Comment by bcoe** [comment]
@tomchentw love it \o/

**Comment by tomchentw** [comment]
Thanks!

**Comment by tomchentw** [comment]
Mind to release a new version on npm?

**Comment by bcoe** [comment]
@tomchentw give this a shot:

`npm i standard-version@next`

thanks a ton for the contribution.

**Comment by tomchentw** [comment]
@bcoe yeah it's working! Thanks :)

**Pull request merged**
