### PR TITLE
fix: always pass version to changelog context

### PR DESCRIPTION
**Pull request by Djaler**
fixes: #326

### CODE REVIEW

**Comment by Djaler** [comment]
This CI warnings are not due to me

**Comment by abcfy2** [comment]
LTGM. Hope this PR could be merged.

**Comment by Djaler** [comment]
@bcoe can you check this, please?

**Comment by bcoe** [comment]
@Djaler thank you for the patch 👍 I'm excited to get `standard-version` working better for non JavaScript projects.

**Pull request merged**
