### PR TITLE
feat: add support for `npm-shrinkwrap.json`

### PR DESCRIPTION
**Pull request by noreiller**
Hi, I use your module since a few weeks, and as I missed this little feature, here it is.
By the way, I fixed the bower test since it didn't check the `bower.json` file. :smile: 
Thank for your great work.
Aurélien

### CODE REVIEW

**Comment by stevemao** [comment]
Could you also add support for `package-lock`? Thanks :)

**Comment by bcoe** [comment]
@stevemao the CLI team at npm tells me that you shouldn't publish the package-lock.json to the registry; and it looks like `npm version` (according to the docs) doesn't implement the version in `package-lock.json`

I say we land this feature, and I'll talk to my coworkers Monday to see if we would want to increment the version in `package-lock.json`.

**Comment by stevemao** [comment]
> you shouldn't publish the package-lock.json to the registry;

Did you mean to publish to the npm registry? The whole workflow we are dealing here doesn't include this step. We only checkin the changes to git. Also I believe `npm publish` doesn't allow you to publish this file and we shouldn't worry about it.

> and it looks like npm version (according to the docs) doesn't implement the version in package-lock.json

I was looking at https://github.com/npm/npm/commit/d654a8e1a73c76b52476760a39e729373fe2c473

> I say we land this feature, and I'll talk to my coworkers Monday to see if we would want to increment the version in package-lock.json.

Sounds good. I honestly don't know if `version` field should be in a lock file since it doesn't seem to add any extra information than the same field in `package.json` 😄

**Comment by bcoe** [comment]
@stevemao I'll follow up tomorrow; and create an issue if the CLI team thinks we should bump the version in `package-lock.json`.

**Comment by zkat** [comment]
You should. `npm version` does (and includes it in the commit). Right now, it's a minor annoyance 'cause the _next_ install will update the version.

**Comment by bcoe** [comment]
@noreiller, zkat literally wrote the book on this -- don't suppose I could convince you to send a follow up pull request.

**Comment by zkat** [comment]
fwiw, y'all should treat `npm-shrinkwrap.json` and `package-lock.json` as interchangeable -- they're the same format, and anything this does to one, it should be able to do to the other.

**Comment by bcoe** [comment]
@noreiller your changes are currently available in `standard-version@next`:

`npm i standard-version@next`, would love your help testing since it's a fairly major change.

**Comment by noreiller** [comment]
Hi @bcoe, I just ran successful tests with `standard-version@next`.
Ok for another PR dedicated to `package-lock`.

**Comment by noreiller** [comment]
PR #190 :smile:

**Comment by bcoe** [comment]
@noreiller awesome 👍

**Pull request merged**
